baseURL: "https://b-anas.me/"
title: " "
description: "Read the latest articales on Ai, Productivity hacks, Language Acquisition,Linux and amazing minimalist open source softwares."
paginate: 9
theme: PaperMod
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: search
      name:     ğŸ”
      url: /search/
      weight: 1
    - identifier: posts
      name: ğŸ—’ï¸ á´˜á´sá´›s
      url: /posts/
      weight: 10
    - identifier: Contact
      name: ğŸ“¬  ğ•®ğ–”ğ–“ğ–™ğ–†ğ–ˆğ–™
      url: /contact/
      weight: 50
    - identifier: About Me 
      name: ğŸ‘¨â€ğŸš€ á´€Ê™á´á´œá´›
      url : /about/
      weight: 40
    - identifier: archives
      name: ğŸ—ƒï¸ á´€Ê€á´„ÊœÉªá´ á´‡s
      url : /archives/
      weight: 30
    - identifier: categories
      name: ğŸ—„ï¸ á´„á´€á´›á´‡É¢á´Ê€Éªá´‡s
      url: /categories/
      weight: 20

params:
  env: production
  title: "ğ””Ğ²Ğ²"
  description: "
    Read the latest articales on Ai, Productivity hacks, Language Acquisition, Linux and amazing minimalist open source softwares."
  keywords: [Blog, Ai, Programming, English, Terminal, Linux]
  author: Anas Boubechra
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false

  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    favicon: "/img/qb_white.svg"

  label:
    icon: "/img/qb_white.svg"

    iconHeight: 40

  cover:

  profileMode:
    enabled: true
    title: "Ñ‚Ğ½Ñ” QÏ…Î±Î·Ñ‚Ï…Ğ¼ Ğ²â„“Î¹Ñ•Ñ• Ğ²â„“Ïƒg"
    subtitle: "Read the latest articales on Ai, Productivity hacks, Language Acquisition,Linux and amazing minimalist open source softwares."
    imageUrl: "/img/qb_white.svg"
    imageWidth: 150
    imageHeight: 150

    buttons:
      - name: Posts
        url: posts
      - name: About 
        url: about 

  socialIcons:
    - name: github
      url: "https://github.com/AnasBoubechra"
    - name: paypal
      url: "https://www.paypal.com/paypalme/banasai?country.x=MA&locale.x=en_US"
    - name: facebook
      url: "https://www.facebook.com/anas.boubechra"
    - name: telegram
      url: "https://t.me/Br_ai"
    - name: RSS
      url: "/posts/index.xml"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

pygmentsUseClasses: true
markup:
    highlight:
        codeFences: true
        guessSyntax: true
        style: friendly
        noClasses: true
